name: Run pytest push or pull request

on:
  push:
    branches: [main, "develop", "feature-*"]
  pull_request:
    branches: [main, "develop", "feature-*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v7.3.0
      - name: Install dependencies
        run: |
          uv sync
      - name: Test with pytest
        run: |
          uv run pytest -v --cov=gomalock
